"""Week 2 before/after — the whole pre-processing chain on one page.

Shows, for one representative subject per site, what each stage actually did to
the image: the raw FLAIR as downloaded, the head mask that bounds N4, the
estimated bias field, the bias-corrected FLAIR, and the skull-stripped brain.

This is the figure that answers "what did Week 2 change?" at a glance, and it
is the one to lead the Week 2 report with. Generated by committed code with the
commit hash burned into the title, never a screenshot (CLAUDE.md Section 5.7).

    code/.venv/bin/python -m preprocessing.make_pipeline_figure
"""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from metadata.config import PROJECT_ROOT
from metadata.derived import (
    BIAS_FIELD,
    BRAIN_MASK,
    FLAIR_N4,
    HEAD_MASK,
    load_derived,
    load_derived_mask,
)
from metadata.loader import load_nifti, load_split, load_wmh_mask, subjects_by_key
from metadata.provenance import get_git_commit_hash, write_manifest
from metadata.runlog import setup_logging

SCRIPT_NAME = "make_pipeline_figure"
OUTPUTS_DIR = PROJECT_ROOT / "preprocessing" / "outputs"
FIGURES_DIR = OUTPUTS_DIR / "figures"
STAGE3_QC = OUTPUTS_DIR / "stage3_skull_strip_qc.csv"


def representative_subjects() -> list[str]:
    """One median-lesion-burden training subject per site — typical, not picked."""
    subjects = subjects_by_key()
    train = load_split("train")
    burden = []
    for key in train:
        subject = subjects[key]
        lesion = load_wmh_mask(subject.mask_path)
        burden.append((subject.site, key, int(lesion.sum())))
    table = pd.DataFrame(burden, columns=["site", "subject_key", "voxels"])
    chosen = []
    for _, group in table.groupby("site"):
        ordered = group.sort_values("voxels").reset_index(drop=True)
        chosen.append(ordered.loc[len(ordered) // 2, "subject_key"])
    return chosen


def main() -> None:
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    logger = setup_logging(SCRIPT_NAME, OUTPUTS_DIR)
    commit = get_git_commit_hash()

    subjects = subjects_by_key()
    keys = representative_subjects()
    logger.info("representative subjects (median lesion burden per site): %s", keys)

    columns = [
        "1. raw FLAIR\n(as downloaded)",
        "2. head mask\n(Stage 1, feeds N4)",
        "3. estimated bias field\n(Stage 2)",
        "4. bias-corrected\n(Stage 2 output)",
        "5. skull-stripped brain\n(Stage 3, R1)",
        "6. brain + reference WMH\n(what Week 3 must find)",
    ]
    fig, axes = plt.subplots(len(keys), len(columns), figsize=(3.0 * len(columns), 3.4 * len(keys)))
    axes = np.atleast_2d(axes)

    for row, key in enumerate(keys):
        subject = subjects[key]
        raw = np.asarray(load_nifti(subject.flair_path).dataobj, dtype=float)
        head = load_derived_mask(key, HEAD_MASK)
        bias = np.asarray(load_derived(key, BIAS_FIELD).dataobj, dtype=float)
        corrected = np.asarray(load_derived(key, FLAIR_N4).dataobj, dtype=float)
        brain = load_derived_mask(key, BRAIN_MASK)
        lesion = load_wmh_mask(subject.mask_path)

        z = int(np.argmax(lesion.sum(axis=(0, 1))))  # the most lesion-bearing slice
        vmax = float(np.percentile(raw[head], 99.5))

        def show(column, image, **kwargs):
            axes[row, column].imshow(image[:, :, z].T[::-1], **kwargs)
            axes[row, column].axis("off")

        show(0, raw, cmap="gray", vmin=0, vmax=vmax)
        show(1, raw, cmap="gray", vmin=0, vmax=vmax)
        axes[row, 1].contour(head[:, :, z].T[::-1], colors="deepskyblue", linewidths=0.9)

        field = np.where(head, bias, np.nan)
        show(2, field, cmap="RdBu_r", vmin=0.8, vmax=1.2)

        show(3, corrected, cmap="gray", vmin=0, vmax=vmax)

        # The stripped panels get their OWN display range, computed from brain
        # voxels only. Reusing the head-derived range would leave Utrecht's
        # brain almost black, because its scalp fat is brighter than anything
        # inside the skull and dominates the scale — and the brain is all Week 3
        # ever sees, so showing it on the scalp's scale misrepresents the input.
        brain_vmax = float(np.percentile(corrected[brain], 99.5))
        stripped = np.where(brain, corrected, 0.0)
        show(4, stripped, cmap="gray", vmin=0, vmax=brain_vmax)

        show(5, stripped, cmap="gray", vmin=0, vmax=brain_vmax)
        axes[row, 5].contour(lesion[:, :, z].T[::-1], colors="lime", linewidths=0.8)

        axes[row, 0].set_ylabel(f"{subject.site}", fontsize=10)
        axes[row, 0].axis("on")
        axes[row, 0].set_xticks([])
        axes[row, 0].set_yticks([])
        axes[row, 0].set_title(
            f"{subject.site} {subject.subject_id}  (axial z={z})", fontsize=8, loc="left"
        )

    for column, label in enumerate(columns):
        axes[0, column].set_title(
            f"{label}\n" + (axes[0, column].get_title() if column == 0 else ""),
            fontsize=9,
        )

    fig.suptitle(
        f"Week 2 pre-processing — raw FLAIR through to skull-stripped brain, "
        f"one subject per site  (commit {commit[:8]})",
        fontsize=12,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    path = FIGURES_DIR / "week2_pipeline_overview.png"
    fig.savefig(path, dpi=125)
    plt.close(fig)
    write_manifest(path, generating_script=f"preprocessing/{SCRIPT_NAME}.py")
    logger.info("wrote %s", path)

    # --- a second figure: what skull stripping removed, in close-up ----------
    fig, axes = plt.subplots(len(keys), 3, figsize=(10.5, 3.4 * len(keys)))
    axes = np.atleast_2d(axes)
    for row, key in enumerate(keys):
        subject = subjects[key]
        raw = np.asarray(load_nifti(subject.flair_path).dataobj, dtype=float)
        head = load_derived_mask(key, HEAD_MASK)
        brain = load_derived_mask(key, BRAIN_MASK)
        lesion = load_wmh_mask(subject.mask_path)
        z = int(np.argmax(lesion.sum(axis=(0, 1))))
        vmax = float(np.percentile(raw[head], 99.5))

        axes[row, 0].imshow(raw[:, :, z].T[::-1], cmap="gray", vmin=0, vmax=vmax)
        axes[row, 0].set_title(f"{subject.site} {subject.subject_id} — original", fontsize=9)

        axes[row, 1].imshow(raw[:, :, z].T[::-1], cmap="gray", vmin=0, vmax=vmax)
        axes[row, 1].contour(brain[:, :, z].T[::-1], colors="red", linewidths=1.0)
        axes[row, 1].set_title("brain mask boundary (red)", fontsize=9)

        # Everything discarded: skull, scalp, and the bright fat that would
        # otherwise be segmented as lesion in Week 3.
        removed = np.where(head & ~brain, raw, np.nan)
        axes[row, 2].imshow(raw[:, :, z].T[::-1], cmap="gray", vmin=0, vmax=vmax, alpha=0.35)
        axes[row, 2].imshow(removed[:, :, z].T[::-1], cmap="autumn", vmin=0, vmax=vmax)
        axes[row, 2].set_title("what was removed (orange)", fontsize=9)

        for column in range(3):
            axes[row, column].axis("off")

    fig.suptitle(
        f"Stage 3 skull stripping — what the brain mask keeps and discards  (commit {commit[:8]})",
        fontsize=12,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    path = FIGURES_DIR / "stage3_skull_strip.png"
    fig.savefig(path, dpi=125)
    plt.close(fig)
    write_manifest(path, generating_script=f"preprocessing/{SCRIPT_NAME}.py")
    logger.info("wrote %s", path)


if __name__ == "__main__":
    main()
