"""Stage 2 report figures — the estimated bias field and its effect.

ROADMAP 5.3 names three deliverables for R3: the estimated bias field as an
image, a before/after intensity-uniformity metric, and agreement with the
organisers' SPM12 correction. The uniformity and agreement numbers come out of
`run_bias_field.py` into stage2_bias_field_qc.csv; this script draws the images.

Figures are generated by committed code and never hand-edited or screenshotted
(CLAUDE.md Section 5.7), and each carries the commit hash so a reader can trace
it back to the exact state that produced it.

    code/.venv/bin/python -m preprocessing.make_stage2_figures
"""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from metadata.config import CODE_ROOT, N4_CONFIG, PROJECT_ROOT
from metadata.derived import BIAS_FIELD, FLAIR_N4, HEAD_MASK, load_derived, load_derived_mask
from metadata.loader import load_nifti, load_split, load_wmh_mask, subjects_by_key
from metadata.provenance import get_git_commit_hash, write_manifest
from metadata.runlog import setup_logging

SCRIPT_NAME = "make_stage2_figures"
OUTPUTS_DIR = CODE_ROOT / "preprocessing" / "outputs"
FIGURES_DIR = OUTPUTS_DIR / "figures"
QC_CSV = OUTPUTS_DIR / "stage2_bias_field_qc.csv"


def _representative_subject_per_site(table: pd.DataFrame) -> list[str]:
    """The median-bias-span subject at each site — typical, not cherry-picked."""
    chosen = []
    for _, group in table.groupby("site"):
        ordered = group.sort_values("bias_span_percent").reset_index(drop=True)
        chosen.append(ordered.loc[len(ordered) // 2, "subject_key"])
    return chosen


def figure_bias_fields(subject_keys: list[str], commit: str) -> None:
    """Original FLAIR, estimated bias field, and corrected FLAIR, one row per site."""
    subjects = subjects_by_key()
    fig, axes = plt.subplots(len(subject_keys), 3, figsize=(11, 3.6 * len(subject_keys)))
    axes = np.atleast_2d(axes)

    for row, key in enumerate(subject_keys):
        subject = subjects[key]
        original = np.asarray(load_nifti(subject.flair_path).dataobj, dtype=float)
        corrected = np.asarray(load_derived(key, FLAIR_N4).dataobj, dtype=float)
        bias = np.asarray(load_derived(key, BIAS_FIELD).dataobj, dtype=float)
        head = load_derived_mask(key, HEAD_MASK)
        lesion = load_wmh_mask(subject.mask_path)

        z = int(np.argmax(lesion.sum(axis=(0, 1))))  # the most lesion-bearing slice
        vmax = np.percentile(original[head], 99.5)

        axes[row, 0].imshow(original[:, :, z].T[::-1], cmap="gray", vmin=0, vmax=vmax)
        axes[row, 0].set_title(f"{subject.site} {subject.subject_id} — original FLAIR", fontsize=9)

        field = np.where(head, bias, np.nan)
        image = axes[row, 1].imshow(field[:, :, z].T[::-1], cmap="RdBu_r", vmin=0.7, vmax=1.3)
        axes[row, 1].set_title("estimated bias field", fontsize=9)
        plt.colorbar(image, ax=axes[row, 1], fraction=0.046)

        axes[row, 2].imshow(corrected[:, :, z].T[::-1], cmap="gray", vmin=0, vmax=vmax)
        axes[row, 2].contour(lesion[:, :, z].T[::-1], colors="lime", linewidths=0.6)
        axes[row, 2].set_title("corrected (reference WMH in green)", fontsize=9)

        for column in range(3):
            axes[row, column].axis("off")

    levels = N4_CONFIG["selected_fitting_levels"]
    fig.suptitle(
        f"Stage 2 — N4 bias field correction at {levels} fitting levels  (commit {commit[:8]})",
        fontsize=11,
    )
    fig.tight_layout()
    path = FIGURES_DIR / "stage2_bias_fields.png"
    fig.savefig(path, dpi=130)
    plt.close(fig)
    write_manifest(path, generating_script=f"code/preprocessing/{SCRIPT_NAME}.py")


def figure_uniformity(table: pd.DataFrame, commit: str) -> None:
    """Before/after uniformity and lesion contrast — the two numbers that decided
    the setting, shown per subject rather than as a single pooled mean."""
    labelled = table.dropna(subset=["cv_before", "cnr_change_percent"])
    fig, axes = plt.subplots(1, 3, figsize=(14, 4.2))
    colours = {"Amsterdam": "#4C72B0", "Singapore": "#DD8452", "Utrecht": "#55A868"}

    for site, group in labelled.groupby("site"):
        axes[0].scatter(group["cv_before"], group["cv_after"], s=26,
                        label=site, color=colours.get(site), alpha=0.85)
    limits = [0, labelled[["cv_before", "cv_after"]].to_numpy().max() * 1.05]
    axes[0].plot(limits, limits, "k--", lw=1, label="no change")
    axes[0].set(xlabel="CV before", ylabel="CV after",
                title="Intensity uniformity within NAWM\n(below the line = more uniform)")
    axes[0].legend(fontsize=8)

    sites = list(colours)
    axes[1].boxplot([labelled[labelled.site == s]["cnr_change_percent"] for s in sites],
                    tick_labels=sites)
    axes[1].axhline(0, color="k", ls="--", lw=1)
    axes[1].set(ylabel="change in lesion-to-WM CNR (%)",
                title="Lesion contrast must not fall\n(the guard against N4 eating lesions)")

    axes[2].boxplot([labelled[labelled.site == s]["bias_span_percent"] for s in sites],
                    tick_labels=sites)
    axes[2].axhspan(28, 38, color="grey", alpha=0.25, label="SPM12 range on this data")
    axes[2].set(ylabel="bias field span removed (%)",
                title="How much inhomogeneity we remove\nvs the organisers' SPM12")
    axes[2].legend(fontsize=8)

    fig.suptitle(f"Stage 2 — N4 quality control across {len(labelled)} training subjects "
                 f"(commit {commit[:8]})", fontsize=11)
    fig.tight_layout()
    path = FIGURES_DIR / "stage2_uniformity.png"
    fig.savefig(path, dpi=130)
    plt.close(fig)
    write_manifest(path, generating_script=f"code/preprocessing/{SCRIPT_NAME}.py")


def main() -> None:
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    logger = setup_logging(SCRIPT_NAME, OUTPUTS_DIR)

    if not QC_CSV.exists():
        raise SystemExit(f"{QC_CSV} not found — run `python -m preprocessing.run_bias_field` first.")

    table = pd.read_csv(QC_CSV)
    commit = get_git_commit_hash()

    train_keys = set(load_split("train"))
    representative = _representative_subject_per_site(table[table.subject_key.isin(train_keys)])
    logger.info("representative subjects (median bias span per site): %s", representative)

    figure_bias_fields(representative, commit)
    figure_uniformity(table, commit)
    logger.info("wrote figures to %s", FIGURES_DIR)


if __name__ == "__main__":
    main()
