"""Build the human-browsable `outputs/` gallery.

This is the presentation layer for the whole project, and from Week 2 onward it
is how results are managed. `preprocessing/outputs/` stays as the working copy
that the pipeline scripts write into; `outputs/` is the curated, plainly-named
version a human opens to see what was done.

Three rules for every figure in here:

1. **It carries its own reference.** Every figure shows the "before" next to the
   "after", inside the same image. A picture of a result you cannot compare
   against anything is not evidence of anything.
2. **It is named in plain words.** `skull-stripped-vs-original.png`, not
   `stage3_fig2.png`. The folder and file names should tell the story without
   opening anything.
3. **It is generated by this script**, never a screenshot, with the git commit
   stamped into the title (CLAUDE.md Section 5.7).

The same three subjects — the median lesion-burden subject at each site — appear
in every figure, so the gallery reads as one continuous story rather than a pile
of unrelated pictures.

    code/.venv/bin/python -m preprocessing.make_outputs
"""

from __future__ import annotations

import shutil

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import ListedColormap
from scipy import ndimage as ndi

from metadata.config import CODE_ROOT, PROJECT_ROOT
from metadata.derived import (
    BIAS_FIELD,
    BRAIN_MASK,
    FLAIR_N4,
    FLAIR_NORM,
    HEAD_MASK,
    TISSUE_SEG,
    load_derived,
    load_derived_mask,
)
from metadata.geometry import voxel_spacing_mm, voxel_volume_mm3
from metadata.loader import load_nifti, load_split, load_wmh_mask, subjects_by_key
from metadata.provenance import get_git_commit_hash, write_manifest
from metadata.runlog import setup_logging
from preprocessing.denoise import clahe, denoise
from preprocessing.morphology import minimum_size_cost, remove_small_components
from preprocessing.tissue_seg import LABEL_WM

SCRIPT_NAME = "make_outputs"
WORKING_OUTPUTS = CODE_ROOT / "preprocessing" / "outputs"
GALLERY = PROJECT_ROOT / "outputs"
WEEK2 = GALLERY / "week2-preprocessing"

SITES = ("Amsterdam", "Singapore", "Utrecht")
LESION_GREEN = "#39FF14"


def _stamp(fig, title: str, subtitle: str, commit: str) -> None:
    """Title + subtitle, spaced by figure height.

    Fixed y-positions collide on short (single-row) figures — the subtitle runs
    straight through the title. Converting a fixed point offset into figure
    fraction keeps the gap constant whatever the figure height.
    """
    height_inches = fig.get_size_inches()[1]
    title_y = 1.0 - (0.18 / height_inches)
    subtitle_y = 1.0 - (0.48 / height_inches)
    fig.suptitle(title, fontsize=14, fontweight="bold", y=title_y)
    fig.text(0.5, subtitle_y, subtitle, ha="center", fontsize=9.5, style="italic", wrap=True)
    fig.text(0.995, 0.004, f"commit {commit[:8]}", ha="right", fontsize=6.5, color="grey")


def _save(fig, path, commit: str, logger) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=130, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    write_manifest(path, generating_script=f"code/preprocessing/{SCRIPT_NAME}.py",
                   extra={"commit": commit})
    logger.info("  %s", path.relative_to(PROJECT_ROOT))


def _panel(axis, image, title, *, vmin=0, vmax=None, cmap="gray"):
    axis.imshow(image.T[::-1], cmap=cmap, vmin=vmin, vmax=vmax)
    axis.set_title(title, fontsize=9)
    axis.axis("off")


def _reference_badge(axis) -> None:
    """Mark which panel is the thing everything else is compared against."""
    axis.set_title(axis.get_title(), fontsize=9, color="#B22222", fontweight="bold")


class Subject:
    """Everything one representative subject contributes to the gallery."""

    def __init__(self, key: str):
        subjects = subjects_by_key()
        self.meta = subjects[key]
        self.key = key
        self.site = self.meta.site
        self.label = f"{self.meta.site} {self.meta.subject_id}"
        image = load_nifti(self.meta.flair_path)
        self.spacing = voxel_spacing_mm(image)
        self.voxel_volume = voxel_volume_mm3(image)
        self.raw = np.asarray(image.dataobj, dtype=float)
        self.t1 = np.asarray(load_nifti(self.meta.t1_path).dataobj, dtype=float)
        self.head = load_derived_mask(key, HEAD_MASK)
        self.brain = load_derived_mask(key, BRAIN_MASK)
        self.bias = np.asarray(load_derived(key, BIAS_FIELD).dataobj, dtype=float)
        self.n4 = np.asarray(load_derived(key, FLAIR_N4).dataobj, dtype=float)
        self.norm = np.asarray(load_derived(key, FLAIR_NORM).dataobj, dtype=float)
        self.tissue = np.asarray(load_derived(key, TISSUE_SEG).dataobj)
        self.lesion = load_wmh_mask(self.meta.mask_path)
        self.z = int(np.argmax(self.lesion.sum(axis=(0, 1))))
        self.raw_vmax = float(np.percentile(self.raw[self.head], 99.5))
        self.brain_vmax = float(np.percentile(self.n4[self.brain], 99.5))

    def slice_of(self, volume):
        return volume[:, :, self.z]


def pick_subjects(logger) -> list[Subject]:
    """Median lesion-burden subject per site — typical, not cherry-picked."""
    subjects = subjects_by_key()
    rows = []
    for key in load_split("train"):
        rows.append({"key": key, "site": subjects[key].site,
                     "vox": int(load_wmh_mask(subjects[key].mask_path).sum())})
    table = pd.DataFrame(rows)
    chosen = []
    for site in SITES:
        group = table[table.site == site].sort_values("vox").reset_index(drop=True)
        chosen.append(group.loc[len(group) // 2, "key"])
    logger.info("representative subjects (median lesion burden per site): %s", chosen)
    return [Subject(k) for k in chosen]


# ---------------------------------------------------------------------------
# 00 — the overview
# ---------------------------------------------------------------------------


def figure_overview(subjects, commit, logger) -> None:
    columns = [
        "1. ORIGINAL SCAN\n(what we downloaded)",
        "2. head found\n(air removed)",
        "3. scanner brightness\ngradient measured",
        "4. gradient removed",
        "5. SKULL REMOVED\n(brain only)",
        "6. BRIGHTNESS NORMALISED\n+ true lesions in green",
    ]
    fig, axes = plt.subplots(len(subjects), 6, figsize=(19, 3.7 * len(subjects)))
    axes = np.atleast_2d(axes)

    for row, s in enumerate(subjects):
        _panel(axes[row, 0], s.slice_of(s.raw), "", vmax=s.raw_vmax)
        _panel(axes[row, 1], s.slice_of(s.raw), "", vmax=s.raw_vmax)
        axes[row, 1].contour(s.slice_of(s.head).T[::-1], colors="deepskyblue", linewidths=0.9)

        field = np.where(s.head, s.bias, np.nan)
        _panel(axes[row, 2], s.slice_of(field), "", vmin=0.85, vmax=1.15, cmap="RdBu_r")

        _panel(axes[row, 3], s.slice_of(s.n4), "", vmax=s.raw_vmax)

        stripped = np.where(s.brain, s.n4, 0.0)
        _panel(axes[row, 4], s.slice_of(stripped), "", vmax=s.brain_vmax)

        _panel(axes[row, 5], s.slice_of(s.norm), "", vmin=0, vmax=2.0)
        axes[row, 5].contour(s.slice_of(s.lesion).T[::-1], colors=LESION_GREEN, linewidths=0.8)

        axes[row, 0].axis("on")
        axes[row, 0].set_xticks([]); axes[row, 0].set_yticks([])
        axes[row, 0].set_ylabel(s.label, fontsize=11, fontweight="bold")
        for spine in axes[row, 0].spines.values():
            spine.set_edgecolor("#B22222"); spine.set_linewidth(2)

    for column, label in enumerate(columns):
        axes[0, column].set_title(label, fontsize=10, pad=10,
                                  fontweight="bold" if column in (0, 4, 5) else "normal",
                                  color="#B22222" if column == 0 else "black")

    _stamp(fig, "WEEK 2 — everything we did to the scans, left to right",
           "Column 1 (red border) is the untouched original. One patient per hospital; "
           "each row is the same brain all the way across.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    _save(fig, WEEK2 / "00-overview" / "full-pipeline-all-sites.png", commit, logger)


# ---------------------------------------------------------------------------
# 01-05 — one figure per step, each against its reference
# ---------------------------------------------------------------------------


def figure_head_mask(subjects, commit, logger) -> None:
    fig, axes = plt.subplots(len(subjects), 3, figsize=(11, 3.7 * len(subjects)))
    axes = np.atleast_2d(axes)
    for row, s in enumerate(subjects):
        _panel(axes[row, 0], s.slice_of(s.raw), f"{s.label}\nBEFORE — original scan", vmax=s.raw_vmax)
        _reference_badge(axes[row, 0])
        _panel(axes[row, 1], s.slice_of(s.raw), "AFTER — head outlined in blue", vmax=s.raw_vmax)
        axes[row, 1].contour(s.slice_of(s.head).T[::-1], colors="deepskyblue", linewidths=1.1)
        sagittal = s.head[s.head.shape[0] // 2]
        raw_sag = s.raw[s.raw.shape[0] // 2]
        aspect = s.spacing[2] / s.spacing[1]
        axes[row, 2].imshow(raw_sag.T[::-1], cmap="gray", vmin=0, vmax=s.raw_vmax, aspect=aspect)
        axes[row, 2].contour(sagittal.T[::-1], colors="deepskyblue", linewidths=1.1)
        axes[row, 2].set_title("side view — same outline", fontsize=9)
        axes[row, 2].axis("off")
    _stamp(fig, "STEP 1 — finding the head",
           "Separates head from the empty air around it. This is NOT skull stripping — "
           "it only exists so the next step has a region to work in.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    _save(fig, WEEK2 / "01-head-found" / "head-outline-vs-original.png", commit, logger)


def figure_bias(subjects, commit, logger) -> None:
    fig, axes = plt.subplots(len(subjects), 4, figsize=(15, 3.7 * len(subjects)))
    axes = np.atleast_2d(axes)
    for row, s in enumerate(subjects):
        _panel(axes[row, 0], s.slice_of(s.raw), f"{s.label}\nBEFORE — original scan", vmax=s.raw_vmax)
        _reference_badge(axes[row, 0])
        field = np.where(s.head, s.bias, np.nan)
        image = axes[row, 1].imshow(s.slice_of(field).T[::-1], cmap="RdBu_r", vmin=0.85, vmax=1.15)
        axes[row, 1].set_title("the scanner's brightness gradient\n(red = too bright, blue = too dim)",
                               fontsize=9)
        axes[row, 1].axis("off")
        plt.colorbar(image, ax=axes[row, 1], fraction=0.046)
        _panel(axes[row, 2], s.slice_of(s.n4), "AFTER — gradient removed", vmax=s.raw_vmax)
        difference = np.where(s.head, s.n4 - s.raw, np.nan)
        limit = float(np.nanpercentile(np.abs(difference), 99))
        image = axes[row, 3].imshow(s.slice_of(difference).T[::-1], cmap="coolwarm",
                                    vmin=-limit, vmax=limit)
        axes[row, 3].set_title("what actually changed\n(before minus after)", fontsize=9)
        axes[row, 3].axis("off")
        plt.colorbar(image, ax=axes[row, 3], fraction=0.046)
    _stamp(fig, "STEP 2 — removing the scanner's brightness gradient  (requirement R3)",
           "Scanners make one side of the brain brighter than the other for electrical reasons. "
           "The gradient is smooth and does NOT follow the anatomy — that is how we know it is "
           "the machine, not the patient.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    _save(fig, WEEK2 / "02-bias-corrected" / "bias-corrected-vs-original.png", commit, logger)


def figure_skull_strip(subjects, commit, logger) -> None:
    fig, axes = plt.subplots(len(subjects), 4, figsize=(15, 3.7 * len(subjects)))
    axes = np.atleast_2d(axes)
    for row, s in enumerate(subjects):
        _panel(axes[row, 0], s.slice_of(s.raw), f"{s.label}\nBEFORE — skull and scalp present",
               vmax=s.raw_vmax)
        _reference_badge(axes[row, 0])
        _panel(axes[row, 1], s.slice_of(s.raw), "brain boundary found (red)", vmax=s.raw_vmax)
        axes[row, 1].contour(s.slice_of(s.brain).T[::-1], colors="red", linewidths=1.1)
        stripped = np.where(s.brain, s.n4, 0.0)
        _panel(axes[row, 2], s.slice_of(stripped), "AFTER — brain only", vmax=s.brain_vmax)
        removed = np.where(s.head & ~s.brain, s.raw, np.nan)
        axes[row, 3].imshow(s.slice_of(s.raw).T[::-1], cmap="gray", vmin=0, vmax=s.raw_vmax, alpha=0.3)
        axes[row, 3].imshow(s.slice_of(removed).T[::-1], cmap="autumn", vmin=0, vmax=s.raw_vmax)
        axes[row, 3].set_title("what was thrown away (orange)", fontsize=9)
        axes[row, 3].axis("off")
    _stamp(fig, "STEP 3 — removing the skull and scalp  (requirement R1)",
           "Scalp fat is the BRIGHTEST thing on these scans — brighter than any lesion. Left in, "
           "it would be labelled as disease. Zero true lesions were lost on any of the 60 patients.",
           commit)
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    _save(fig, WEEK2 / "03-skull-stripped" / "skull-stripped-vs-original.png", commit, logger)


def figure_tissue(subjects, commit, logger) -> None:
    colours = ListedColormap([(0, 0, 0, 0), (0.25, 0.45, 1, .85),
                              (0.2, 0.9, 0.35, .85), (1, 0.88, 0.2, .85)])
    fig, axes = plt.subplots(len(subjects), 3, figsize=(11.5, 3.7 * len(subjects)))
    axes = np.atleast_2d(axes)
    for row, s in enumerate(subjects):
        t1_vmax = float(np.percentile(s.t1[s.brain], 99))
        _panel(axes[row, 0], s.slice_of(s.t1), f"{s.label}\nBEFORE — the T1 scan", vmax=t1_vmax)
        _reference_badge(axes[row, 0])
        axes[row, 1].imshow(s.slice_of(s.t1).T[::-1], cmap="gray", vmin=0, vmax=t1_vmax)
        axes[row, 1].imshow(s.slice_of(s.tissue).T[::-1], cmap=colours, vmin=0, vmax=3,
                            interpolation="nearest")
        axes[row, 1].set_title("AFTER — fluid (blue), grey (green),\nwhite matter (yellow)", fontsize=9)
        axes[row, 1].axis("off")
        white = np.where(s.tissue == LABEL_WM, 1.0, np.nan)
        axes[row, 2].imshow(s.slice_of(s.t1).T[::-1], cmap="gray", vmin=0, vmax=t1_vmax)
        axes[row, 2].imshow(s.slice_of(white).T[::-1],
                            cmap=ListedColormap([(1, 0.88, 0.2, 0.65)]))
        axes[row, 2].contour(s.slice_of(s.lesion).T[::-1], colors="red", linewidths=1.0)
        axes[row, 2].set_title("white matter only, with true\nlesions outlined in red", fontsize=9)
        axes[row, 2].axis("off")
    _stamp(fig, "STEP 4 — sorting the brain into three tissue types",
           "Needed so the next step knows where HEALTHY white matter is. Note in the right-hand "
           "panel: lesions fall OUTSIDE the yellow — they look dark on T1, which is exactly why "
           "this makes a good 'healthy tissue' reference.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    _save(fig, WEEK2 / "04-tissue-sorted" / "tissue-types-vs-t1.png", commit, logger)


def figure_normalisation(subjects, commit, logger) -> None:
    fig, axes = plt.subplots(len(subjects), 2, figsize=(8.5, 3.9 * len(subjects)))
    axes = np.atleast_2d(axes)
    for row, s in enumerate(subjects):
        masked = np.where(s.brain, s.raw, 0.0)
        _panel(axes[row, 0], s.slice_of(masked),
               f"{s.label}\nBEFORE — same display setting for all 3", vmin=0, vmax=1200)
        _reference_badge(axes[row, 0])
        _panel(axes[row, 1], s.slice_of(s.norm), "AFTER — same display setting for all 3",
               vmin=0, vmax=2.0)
    _stamp(fig, "STEP 5 — putting all three hospitals on one brightness scale  (requirement R2)",
           "Both columns use ONE identical display setting across all three hospitals. Before: they "
           "look like scans of different things. After: comparable. Healthy white matter now = 1.0 "
           "everywhere, lesions = 1.4-1.6.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    _save(fig, WEEK2 / "05-brightness-normalised" / "normalised-vs-original.png", commit, logger)


# ---------------------------------------------------------------------------
# 06-07 — the two things we tested and did NOT adopt
# ---------------------------------------------------------------------------


def figure_denoising_rejected(subject, commit, logger) -> None:
    """Zoom where the SMALL lesions are, and mark which ones each filter destroys.

    An earlier version cropped around the largest lesion in the slice. Large
    lesions survive every filter, so the figure argued the opposite of the
    finding. It now centres on the slice richest in small lesions and colours
    each lesion by whether it survived, which is the actual claim.
    """
    small_threshold = 10
    labelled, n = ndi.label(subject.lesion, structure=np.ones((3, 3, 3)))
    sizes = np.bincount(labelled.ravel())[1:]
    small_ids = {i + 1 for i in range(n) if sizes[i] <= small_threshold}
    if not small_ids:
        small_ids = {int(np.argmin(sizes)) + 1}

    small_mask = np.isin(labelled, list(small_ids))
    z = int(np.argmax(small_mask.sum(axis=(0, 1))))
    coords = np.argwhere(small_mask[:, :, z])
    cx, cy = coords.mean(axis=0).astype(int)
    half = 38
    x0, x1 = max(0, cx - half), min(subject.norm.shape[0], cx + half)
    y0, y1 = max(0, cy - half), min(subject.norm.shape[1], cy + half)

    variants = [("BEFORE — no filtering", subject.norm)]
    for name, method in (("anisotropic diffusion", "curvature_anisotropic_diffusion"),
                         ("Gaussian blur", "gaussian")):
        filtered = denoise(subject.norm, subject.spacing, method=method)
        variants.append((name, np.where(subject.brain, filtered, 0.0)))
    variants.append(("CLAHE contrast boost", clahe(subject.norm, subject.brain)))

    visible = [i for i in small_ids if (labelled[:, :, z] == i).any()]
    fig, axes = plt.subplots(1, len(variants), figsize=(4.1 * len(variants), 5.4))

    for column, (name, volume) in enumerate(variants):
        axes[column].imshow(volume[x0:x1, y0:y1, z].T[::-1], cmap="gray", vmin=0, vmax=2.0)
        destroyed = 0
        for lesion_id in visible:
            component = labelled == lesion_id
            before = float(subject.norm[component].mean()) - 1.0
            after = float(volume[component].mean()) - 1.0
            survived = before <= 0 or (after / before) >= 0.5
            destroyed += 0 if survived else 1
            outline = (component[x0:x1, y0:y1, z]).T[::-1]
            axes[column].contour(outline, colors=LESION_GREEN if survived else "red",
                                 linewidths=1.4)
        if column == 0:
            caption = "all lesions intact"
        elif name.startswith("CLAHE"):
            # CLAHE loses no lesions, but that is not a pass — it amplifies
            # everything including noise (-57% contrast-to-noise measured) and
            # destroys the 1.0 = white matter scale. Without this the panel
            # reads as though CLAHE were the good option.
            caption = "0 lesions lost, but look at the noise:\ncontrast-to-noise fell 57%"
        else:
            caption = (f"{destroyed} of {len(visible)} small lesions\n"
                       "lost over half their visibility")
        axes[column].set_title(f"{name}\n{caption}", fontsize=9.5,
                               color="#B22222" if column == 0 else "black",
                               fontweight="bold" if column == 0 else "normal")
        axes[column].axis("off")

    _stamp(fig, "STEP 6 — image smoothing: TESTED AND REJECTED",
           f"Close-up on the small lesions of {subject.label}. GREEN = lesion survived, "
           "RED = lost over half its visibility. Half the lesions in this dataset are 5 voxels "
           "or smaller, which is exactly what smoothing erases.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.88))
    _save(fig, WEEK2 / "06-smoothing-REJECTED" / "why-smoothing-was-rejected.png", commit, logger)


def figure_morphology_cost(subject, commit, logger) -> None:
    thresholds = (3, 5, 10)
    fig, axes = plt.subplots(1, len(thresholds) + 2, figsize=(4.0 * (len(thresholds) + 2), 4.6))

    stripped = np.where(subject.brain, subject.norm, 0.0)
    axes[0].imshow(subject.slice_of(stripped).T[::-1], cmap="gray", vmin=0, vmax=2.0)
    axes[0].contour(subject.slice_of(subject.lesion).T[::-1], colors=LESION_GREEN, linewidths=1.0)
    axes[0].set_title("BEFORE — all true lesions", fontsize=10, color="#B22222", fontweight="bold")
    axes[0].axis("off")

    for column, threshold in enumerate(thresholds, start=1):
        kept, info = remove_small_components(subject.lesion, threshold)
        lost = subject.lesion & ~kept
        axes[column].imshow(subject.slice_of(stripped).T[::-1], cmap="gray", vmin=0, vmax=2.0)
        axes[column].contour(subject.slice_of(kept).T[::-1], colors=LESION_GREEN, linewidths=1.0)
        if lost.any():
            axes[column].contour(subject.slice_of(lost).T[::-1], colors="red", linewidths=1.2)
        axes[column].set_title(f"delete blobs under {threshold} voxels\n"
                               f"{info['components_removed']} of {info['components_before']} "
                               f"lesions deleted (red)", fontsize=9)
        axes[column].axis("off")

    rows = minimum_size_cost(subject.lesion, subject.voxel_volume, (2, 3, 5, 10, 20))
    table = pd.DataFrame(rows)
    axis = axes[-1]
    axis.plot(table.minimum_voxels, 100 * table.lesion_count_fraction_removed,
              "o-", color="#B22222", label="% of LESIONS lost")
    axis.plot(table.minimum_voxels, 100 * table.volume_fraction_removed,
              "s-", color="#4C72B0", label="% of VOLUME lost")
    axis.set(xlabel="delete blobs smaller than (voxels)", ylabel="percent lost",
             title="the trap, as a graph")
    axis.legend(fontsize=8)
    axis.grid(alpha=0.3)

    _stamp(fig, "STEP 7 — the clean-up tool Week 3 will use, and what it costs",
           "Deleting small blobs removes false alarms but also real lesions. The graph is the point: "
           "the red line (lesions lost) shoots up while the blue line (volume lost) barely moves — "
           "so a volume-based score would call this harmless when it is not.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.90))
    _save(fig, WEEK2 / "07-cleanup-tools" / "cost-of-deleting-small-blobs.png", commit, logger)


# ---------------------------------------------------------------------------
# quality checks — copied from the working outputs, renamed plainly
# ---------------------------------------------------------------------------


COPIES = {
    "stage5_normalisation_histograms.png":
        "05-brightness-normalised/brightness-histograms-before-after.png",
    "stage2_uniformity.png": "02-bias-corrected/correction-quality-all-60-patients.png",
    "stage3_worst_cases.png": "quality-checks/skull-stripping-6-worst-patients.png",
    "stage3_contact_sheet.png": "quality-checks/skull-stripping-all-60-patients.png",
    "stage1_head_volumes.png": "quality-checks/head-size-consistency-all-60.png",
}


def copy_working_figures(commit, logger) -> None:
    source_dir = WORKING_OUTPUTS / "figures"
    for source_name, destination in COPIES.items():
        source = source_dir / source_name
        if not source.exists():
            logger.warning("  missing working figure, skipped: %s", source_name)
            continue
        target = WEEK2 / destination
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        logger.info("  %s  (copied)", target.relative_to(PROJECT_ROOT))


def write_readme(subjects, commit) -> None:
    GALLERY.mkdir(parents=True, exist_ok=True)
    names = ", ".join(s.label for s in subjects)
    (GALLERY / "README.md").write_text(f"""# outputs/

Every result, in the order it happened, named in plain words.

**How to read these.** Every image contains its own point of comparison. The
panel with the **red title or red border is the "before"** — the untouched
original — and everything to the right of it is what we did. No image here needs
another image to make sense of it.

Start with **`week2-preprocessing/00-overview/full-pipeline-all-sites.png`** — it
shows the whole week left to right on one page.

## week2-preprocessing/

| Folder | What it shows | Requirement |
|---|---|---|
| `00-overview/` | **Start here.** The entire week, left to right, one row per hospital | — |
| `01-head-found/` | Separating head from empty air | — |
| `02-bias-corrected/` | Removing the scanner's brightness gradient | **R3** |
| `03-skull-stripped/` | Removing skull and scalp | **R1** |
| `04-tissue-sorted/` | Sorting brain into fluid / grey / white matter | — |
| `05-brightness-normalised/` | Putting all three hospitals on one scale | **R2** |
| `06-smoothing-REJECTED/` | A method we tested and chose NOT to use, with the evidence | — |
| `07-cleanup-tools/` | Tools built for Week 3, and what they cost | — |
| `quality-checks/` | Every patient checked, not just the pretty ones | — |

## The patients shown

{names} — the **median lesion-burden patient at each hospital**, so they are
typical rather than flattering. The same three appear in every figure, so the
gallery reads as one continuous story.

## Regenerating

```
code/.venv/bin/python -m preprocessing.make_outputs
```

Every figure is produced by that one script and stamped with the git commit it
came from. Nothing here is a screenshot or hand-edited, so any figure can be
traced back to the exact code that made it.

`preprocessing/outputs/` remains the pipeline's working directory — raw QC
tables and the figures the individual stage scripts emit. This folder is the
curated version for humans.

Generated from commit `{commit[:8]}`.
""")


def main() -> None:
    logger = setup_logging(SCRIPT_NAME, WORKING_OUTPUTS)
    commit = get_git_commit_hash()
    subjects = pick_subjects(logger)

    logger.info("writing gallery to %s", GALLERY)
    figure_overview(subjects, commit, logger)
    figure_head_mask(subjects, commit, logger)
    figure_bias(subjects, commit, logger)
    figure_skull_strip(subjects, commit, logger)
    figure_tissue(subjects, commit, logger)
    figure_normalisation(subjects, commit, logger)
    figure_denoising_rejected(subjects[1], commit, logger)
    figure_morphology_cost(subjects[2], commit, logger)
    copy_working_figures(commit, logger)
    write_readme(subjects, commit)

    total = sum(1 for _ in GALLERY.rglob("*.png"))
    logger.info("done — %d figures in outputs/", total)


if __name__ == "__main__":
    main()
