"""Week 4 gallery — the labelling and measurement figures (R5-R9).

Same three rules the Week 2 and Week 3 galleries follow:

1. **Every figure carries its own reference inside the image.** A ventricle
   outline on its own proves nothing; the un-annotated image has to sit beside
   it so a reader can judge the outline rather than take it on trust.
2. **Pick the slice with the most lesion, never the middle slice.** Week 1
   learned this the hard way: Amsterdam's FLAIR is 3D-acquired with a much
   larger superior-inferior field of view, so `shape[2]//2` lands on an orbital
   slice there while being mid-brain everywhere else.
3. **Generated by this script**, never a screenshot, with the commit stamped on.

    code/.venv/bin/python -m features.make_outputs
"""

from __future__ import annotations

import matplotlib
matplotlib.use("Agg")

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from metadata.config import CODE_ROOT, PROJECT_ROOT
from metadata.derived import BRAIN_MASK, PRED_WMH, VENTRICLES, derived_exists, load_derived_mask
from metadata.loader import load_nifti, load_split, load_wmh_mask, subjects_by_key
from metadata.provenance import get_git_commit_hash, write_manifest
from metadata.runlog import setup_logging
from features.periventricular import split_periventricular_deep

SCRIPT_NAME = "make_outputs"
OUTPUTS_DIR = CODE_ROOT / "features" / "outputs"
WEEK4 = PROJECT_ROOT / "outputs" / "week4-labelling"

VENTRICLE_C = "#00BFFF"   # blue   — the structure we measure from
PERIVENT_C = "#FFD700"    # gold   — within 10 mm
DEEP_C = "#FF3B30"        # red    — beyond 10 mm
TRUTH_C = "#39FF14"       # green  — the expert reference


def _stamp(fig, title, subtitle, commit):
    """Title and caption, positioned in INCHES from the top.

    Figure coordinates are fractions of the figure, so a fixed y collides on a
    tall figure and floats away on a short one. Earlier this produced a title
    printed straight through its own caption on the three-row panels. Offsets
    are therefore converted from inches, and the caption is placed by its TOP
    edge so extra wrapped lines grow downward into the margin rather than
    upward into the title.
    """
    height = fig.get_size_inches()[1]
    fig.suptitle(title, fontsize=14, fontweight="bold", y=1.0 - 0.22 / height)
    fig.text(0.5, 1.0 - 0.52 / height, subtitle, ha="center", va="top",
             fontsize=9.5, style="italic", wrap=True)
    fig.text(0.995, 0.004, f"commit {commit[:8]}", ha="right", fontsize=6.5, color="grey")


def _reserve(fig, inches=1.15):
    """Leave `inches` of clear space at the top for the title block."""
    height = fig.get_size_inches()[1]
    fig.tight_layout(rect=[0, 0, 1, 1.0 - inches / height])


def _save(fig, path, commit, logger):
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=130, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    write_manifest(path, generating_script=f"code/features/{SCRIPT_NAME}.py",
                   extra={"commit": commit})
    logger.info("  %s", path.relative_to(PROJECT_ROOT))


def _panel(axis, image, title, *, cmap="gray"):
    axis.imshow(np.rot90(image), cmap=cmap)
    axis.set_title(title, fontsize=9)
    axis.axis("off")


def _overlay(axis, mask, colour, alpha=0.85):
    rgba = np.zeros((*mask.shape, 4))
    rgba[mask] = [*matplotlib.colors.to_rgb(colour), alpha]
    axis.imshow(np.rot90(rgba))


def _busiest_slice(mask: np.ndarray) -> int:
    """The slice with the most lesion voxels — see rule 2 in the docstring."""
    per_slice = mask.reshape(-1, mask.shape[2]).sum(axis=0)
    return int(np.argmax(per_slice))


def _one_per_site(keys, subjects):
    chosen, seen = {}, set()
    for key in keys:
        site = subjects[key].site
        if site not in seen and derived_exists(key, VENTRICLES):
            seen.add(site)
            chosen[site] = key
    return chosen


# --------------------------------------------------------------------------


def figure_ventricles(chosen, subjects, commit, logger):
    """Did SynthSeg find the ventricles? Raw image beside the outline."""
    fig, axes = plt.subplots(len(chosen), 3, figsize=(10.5, 3.5 * len(chosen)))
    if len(chosen) == 1:
        axes = axes[None, :]

    for row, (site, key) in enumerate(sorted(chosen.items())):
        subject = subjects[key]
        flair = np.asarray(load_nifti(subject.flair_path).dataobj).astype(float)
        t1 = np.asarray(load_nifti(subject.t1_path).dataobj).astype(float)
        vent = load_derived_mask(key, VENTRICLES)
        z = _busiest_slice(vent)

        _panel(axes[row, 0], t1[:, :, z], "T1 — what SynthSeg was given\n(no markings)")
        _panel(axes[row, 1], t1[:, :, z], "T1 + ventricles found")
        _overlay(axes[row, 1], vent[:, :, z], VENTRICLE_C, alpha=0.55)
        _panel(axes[row, 2], flair[:, :, z], "same outline on FLAIR\n(where the lesions live)")
        _overlay(axes[row, 2], vent[:, :, z], VENTRICLE_C, alpha=0.55)
        axes[row, 0].set_ylabel(site, fontsize=11, fontweight="bold")
        axes[row, 0].axis("on")
        axes[row, 0].set_xticks([]); axes[row, 0].set_yticks([])

    _stamp(fig, "Step 1 — finding the ventricles (R5)",
           "SynthSeg on the raw T1, chosen by measurement. The left column is the unmarked "
           "input, so the outline can be judged rather than taken on trust.", commit)
    _reserve(fig)
    _save(fig, WEEK4 / "01-ventricles-found" / "ventricles_on_t1_and_flair.png", commit, logger)


def figure_periventricular_split(chosen, subjects, commit, logger):
    """The actual R5 deliverable: which lesions are near the ventricle."""
    fig, axes = plt.subplots(len(chosen), 4, figsize=(13.5, 3.4 * len(chosen)))
    if len(chosen) == 1:
        axes = axes[None, :]

    for row, (site, key) in enumerate(sorted(chosen.items())):
        subject = subjects[key]
        flair = np.asarray(load_nifti(subject.flair_path).dataobj).astype(float)
        reference = load_wmh_mask(subject.mask_path)
        vent = load_derived_mask(key, VENTRICLES)
        spacing = np.abs(np.diag(load_nifti(subject.flair_path).affine))[:3]
        split = split_periventricular_deep(reference, vent, spacing, threshold_mm=10.0)
        z = _busiest_slice(reference)

        _panel(axes[row, 0], flair[:, :, z], "FLAIR — the raw image\n(no markings)")
        _panel(axes[row, 1], flair[:, :, z], "expert lesions (all)")
        _overlay(axes[row, 1], reference[:, :, z], TRUTH_C)
        _panel(axes[row, 2], flair[:, :, z], "ventricles (blue)\nmeasured from these")
        _overlay(axes[row, 2], split["ventricles_used"][:, :, z], VENTRICLE_C, alpha=0.5)
        _panel(axes[row, 3], flair[:, :, z], "SPLIT: gold ≤10 mm, red >10 mm")
        _overlay(axes[row, 3], split["periventricular"][:, :, z], PERIVENT_C)
        _overlay(axes[row, 3], split["deep"][:, :, z], DEEP_C)
        axes[row, 0].set_ylabel(site, fontsize=11, fontweight="bold")
        axes[row, 0].axis("on")
        axes[row, 0].set_xticks([]); axes[row, 0].set_yticks([])

    # In the margin, not on top of a brain — an overlay legend hid the very
    # anatomy the panel exists to show.
    fig.legend(handles=[
        mpatches.Patch(color=TRUTH_C, label="expert lesions"),
        mpatches.Patch(color=VENTRICLE_C, label="ventricle"),
        mpatches.Patch(color=PERIVENT_C, label="periventricular (≤10 mm)"),
        mpatches.Patch(color=DEEP_C, label="deep (>10 mm)"),
    ], loc="lower center", ncol=4, fontsize=8.5, frameon=False,
        bbox_to_anchor=(0.5, -0.012))

    _stamp(fig, "Step 2 — periventricular vs deep (R5)",
           "Distance in MILLIMETRES, not voxels — slices are 3.00 mm against 0.56-1.30 mm in "
           "plane. Panels build left to right so every step can be checked.", commit)
    _reserve(fig)
    _save(fig, WEEK4 / "02-periventricular-vs-deep" / "the_split_explained.png", commit, logger)


def figure_sensitivity(features, commit, logger):
    """How much does the answer depend on the 10 mm constant?"""
    reference = features[features.source == "reference"].copy()
    cols = {5.0: "periventricular_fraction_at_5mm",
            10.0: "periventricular_fraction",
            15.0: "periventricular_fraction_at_15mm"}
    present = {k: c for k, c in cols.items() if c in reference.columns}
    if not present:
        logger.warning("  no R5 columns yet — skipping sensitivity figure")
        return

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.4))
    sites = sorted(reference.site.unique())
    width = 0.25
    x = np.arange(len(sites))
    for index, (threshold, col) in enumerate(sorted(present.items())):
        means = [100 * reference[reference.site == s][col].mean() for s in sites]
        axes[0].bar(x + (index - 1) * width, means, width,
                    label=f"{threshold:g} mm", edgecolor="black", linewidth=0.5)
    axes[0].set_xticks(x); axes[0].set_xticklabels(sites)
    axes[0].set_ylabel("% of lesion volume called periventricular")
    axes[0].set_title("Sensitivity to the cut-off, by site", fontsize=10)
    axes[0].legend(title="threshold", fontsize=8)
    axes[0].grid(axis="y", alpha=0.3)

    for threshold, col in sorted(present.items()):
        axes[1].hist(100 * reference[col].dropna(), bins=18, alpha=0.55,
                     label=f"{threshold:g} mm", edgecolor="black", linewidth=0.4)
    axes[1].set_xlabel("% periventricular, per subject")
    axes[1].set_ylabel("subjects")
    axes[1].set_title("Spread across the 60 subjects", fontsize=10)
    axes[1].legend(fontsize=8)
    axes[1].grid(axis="y", alpha=0.3)

    _stamp(fig, "Does the 10 mm rule actually matter?",
           "10 mm follows DeCarli 2005 (also UK Biobank, FSL BIANCA). Reporting 5 and 15 mm "
           "beside it turns a hard-coded constant into a stated analysis rather than an "
           "unexamined assumption.", commit)
    _reserve(fig, 1.0)
    _save(fig, WEEK4 / "03-does-the-threshold-matter" / "sensitivity_5_10_15mm.png",
          commit, logger)


def figure_measurements(features, commit, logger):
    """R6-R9, expert against ours — the honest side-by-side."""
    have_pred = (features.source == "prediction").any()
    panels = [("n_lesions", "Lesion count (R6)", "lesions"),
              ("total_lesion_volume_ml", "Total burden (R7)", "mL"),
              ("largest_lesion_feret_mm", "Largest lesion (R8)", "mm"),
              ("hemisphere_ratio", "Left/right spread (R9)", "ratio")]
    panels = [p for p in panels if p[0] in features.columns]

    fig, axes = plt.subplots(1, len(panels), figsize=(3.5 * len(panels), 4.2))
    if len(panels) == 1:
        axes = [axes]
    ref = features[features.source == "reference"]
    pred = features[features.source == "prediction"] if have_pred else None

    for axis, (col, title, unit) in zip(axes, panels):
        if have_pred:
            merged = ref[["subject_key", col]].merge(
                pred[["subject_key", col]], on="subject_key", suffixes=("_ref", "_pred"))
            axis.scatter(merged[f"{col}_ref"], merged[f"{col}_pred"], s=22,
                         alpha=0.75, edgecolor="black", linewidth=0.4)
            lo = float(min(merged[f"{col}_ref"].min(), merged[f"{col}_pred"].min()))
            hi = float(max(merged[f"{col}_ref"].max(), merged[f"{col}_pred"].max()))
            axis.plot([lo, hi], [lo, hi], "--", color="grey", linewidth=1)
            axis.set_xlabel(f"expert ({unit})", fontsize=8)
            axis.set_ylabel(f"ours ({unit})", fontsize=8)
            r = merged[f"{col}_ref"].corr(merged[f"{col}_pred"])
            axis.set_title(f"{title}\nagreement r = {r:.3f}", fontsize=9)
        else:
            axis.hist(ref[col].dropna(), bins=18, edgecolor="black", linewidth=0.4)
            axis.set_xlabel(unit, fontsize=8)
            axis.set_title(title, fontsize=9)
        axis.grid(alpha=0.3)

    _stamp(fig, "Step 3 — the measurements (R6-R9)",
           "Every feature computed TWICE: once from the expert mask, once from our "
           "prediction. The dashed line is perfect agreement. Computing both is what keeps "
           "Weeks 5-6 from training on its own output.", commit)
    _reserve(fig, 1.0)
    _save(fig, WEEK4 / "04-the-measurements" / "expert_vs_ours.png", commit, logger)


def main() -> None:
    logger = setup_logging(SCRIPT_NAME, OUTPUTS_DIR)
    commit = get_git_commit_hash()
    WEEK4.mkdir(parents=True, exist_ok=True)

    subjects = subjects_by_key()
    keys = load_split("train") + load_split("val")
    chosen = _one_per_site(keys, subjects)
    if not chosen:
        raise SystemExit("no ventricle masks yet — run features.run_synthseg first")
    logger.info("Week 4 gallery, showcase subjects: %s", chosen)

    figure_ventricles(chosen, subjects, commit, logger)
    figure_periventricular_split(chosen, subjects, commit, logger)

    features_csv = OUTPUTS_DIR / "features.csv"
    if features_csv.exists():
        features = pd.read_csv(features_csv)
        figure_sensitivity(features, commit, logger)
        figure_measurements(features, commit, logger)
    else:
        logger.warning("features.csv missing — run features.run_features first")

    logger.info("gallery written to %s", WEEK4.relative_to(PROJECT_ROOT))


if __name__ == "__main__":
    main()
