"""Build the Week 3 section of the `outputs/` gallery.

Same three rules as the Week 2 gallery (`preprocessing/make_outputs.py`): every
figure carries its own point of comparison, is named in plain words, and is
generated by committed code with the commit stamped on it. Each week's figure
code lives with that week's pipeline code; the gallery they write into is shared.

    code/.venv/bin/python -m segmentation.make_outputs
"""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import ndimage as ndi

from metadata.config import PROJECT_ROOT
from metadata.derived import (
    BRAIN_MASK,
    FLAIR_NORM,
    PRED_WMH,
    TISSUE_SEG,
    load_derived,
    load_derived_mask,
)
from metadata.geometry import voxel_spacing_mm, voxel_volume_mm3
from metadata.loader import load_nifti, load_split, load_wmh_mask, subjects_by_key
from metadata.provenance import get_git_commit_hash, write_manifest
from metadata.runlog import setup_logging
from segmentation.threshold import threshold_segment

SCRIPT_NAME = "make_outputs"
OUTPUTS_DIR = PROJECT_ROOT / "segmentation" / "outputs"
WEEK3 = PROJECT_ROOT / "outputs" / "week3-segmentation"

TRUTH = "#39FF14"      # green  — the reference standard
PREDICTION = "#FF3B30"  # red    — what we predicted
ROUTE_A = dict(threshold=1.40, min_size_voxels=5)


def _stamp(fig, title, subtitle, commit):
    height = fig.get_size_inches()[1]
    fig.suptitle(title, fontsize=14, fontweight="bold", y=1.0 - 0.18 / height)
    fig.text(0.5, 1.0 - 0.48 / height, subtitle, ha="center", fontsize=9.5, style="italic")
    fig.text(0.995, 0.004, f"commit {commit[:8]}", ha="right", fontsize=6.5, color="grey")


def _save(fig, path, commit, logger):
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=130, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    write_manifest(path, generating_script=f"segmentation/{SCRIPT_NAME}.py",
                   extra={"commit": commit})
    logger.info("  %s", path.relative_to(PROJECT_ROOT))


def _legend(axis):
    axis.legend(handles=[
        mpatches.Patch(color=TRUTH, label="TRUE lesions (expert)"),
        mpatches.Patch(color=PREDICTION, label="what we predicted"),
    ], loc="lower right", fontsize=8, framealpha=0.85)


class Case:
    def __init__(self, key):
        self.key = key
        self.meta = subjects_by_key()[key]
        self.label = f"{self.meta.site} {self.meta.subject_id}"
        image = load_nifti(self.meta.flair_path)
        self.spacing = voxel_spacing_mm(image)
        self.voxel_volume = voxel_volume_mm3(image)
        self.norm = np.asarray(load_derived(key, FLAIR_NORM).dataobj, dtype=float)
        self.brain = load_derived_mask(key, BRAIN_MASK)
        self.tissue = np.asarray(load_derived(key, TISSUE_SEG).dataobj)
        self.truth = load_wmh_mask(self.meta.mask_path)
        self.pred = load_derived_mask(key, PRED_WMH)
        self.z = int(np.argmax(self.truth.sum(axis=(0, 1))))

    def route_a(self):
        prediction, _ = threshold_segment(
            self.norm, self.brain, tissue_labels=self.tissue, exclude_csf=True, **ROUTE_A
        )
        return prediction

    def panel(self, axis, *, show_truth=True, show_pred=True, z=None, crop=None):
        z = self.z if z is None else z
        image, truth, pred = self.norm[:, :, z], self.truth[:, :, z], self.pred[:, :, z]
        if crop is not None:
            (x0, x1), (y0, y1) = crop
            image, truth, pred = image[x0:x1, y0:y1], truth[x0:x1, y0:y1], pred[x0:x1, y0:y1]
        axis.imshow(image.T[::-1], cmap="gray", vmin=0, vmax=2.0)
        if show_truth and truth.any():
            axis.contour(truth.T[::-1], colors=TRUTH, linewidths=1.2)
        if show_pred and pred.any():
            axis.contour(pred.T[::-1], colors=PREDICTION, linewidths=1.2)
        axis.axis("off")


def figure_a_vs_c(scores, commit, logger):
    """The headline: simple method vs network, same patients, same slices."""
    subjects = subjects_by_key()
    val = set(load_split("val"))
    chosen = []
    for site in ("Amsterdam", "Singapore", "Utrecht"):
        candidates = [k for k in val if subjects[k].site == site]
        chosen.append(sorted(candidates)[0])

    fig, axes = plt.subplots(len(chosen), 3, figsize=(12.5, 4.1 * len(chosen)))
    axes = np.atleast_2d(axes)
    for row, key in enumerate(chosen):
        case = Case(key)
        a_pred = case.route_a()
        row_scores = scores[scores.subject_key == key].iloc[0]

        case.panel(axes[row, 0], show_truth=True, show_pred=False)
        axes[row, 0].set_title(f"{case.label}\nTRUE lesions (what we must find)",
                               fontsize=10, color="#B22222", fontweight="bold")

        axes[row, 1].imshow(case.norm[:, :, case.z].T[::-1], cmap="gray", vmin=0, vmax=2.0)
        axes[row, 1].contour(case.truth[:, :, case.z].T[::-1], colors=TRUTH, linewidths=1.2)
        if a_pred[:, :, case.z].any():
            axes[row, 1].contour(a_pred[:, :, case.z].T[::-1], colors=PREDICTION, linewidths=1.2)
        axes[row, 1].set_title("METHOD 1: brightness cut-off\n(simple)", fontsize=10)
        axes[row, 1].axis("off")

        case.panel(axes[row, 2])
        axes[row, 2].set_title(f"METHOD 2: neural network\nDice {row_scores.dice:.3f}",
                               fontsize=10, fontweight="bold")
        if row == 0:
            _legend(axes[row, 2])

    _stamp(fig, "WEEK 3 — finding the lesions: simple method vs neural network",
           "Green = the expert's answer. Red = ours. The middle column marks far too much; "
           "the right column tracks the green closely. Held-out patients the network never "
           "trained on. Dice 0.43 -> 0.81.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    _save(fig, WEEK3 / "00-overview" / "simple-method-vs-neural-network.png", commit, logger)


def figure_best_and_worst(scores, commit, logger):
    """Best, typical and worst — so the average is not the only thing shown."""
    ranked = scores.sort_values("dice").reset_index(drop=True)
    picks = [("WORST", ranked.iloc[0]), ("TYPICAL", ranked.iloc[len(ranked) // 2]),
             ("BEST", ranked.iloc[-1])]

    fig, axes = plt.subplots(1, 3, figsize=(13.5, 5.2))
    for column, (label, row) in enumerate(picks):
        case = Case(row.subject_key)
        case.panel(axes[column])
        axes[column].set_title(
            f"{label} of 60\n{case.label} — Dice {row.dice:.3f}\n"
            f"found {row.lesion_recall:.0%} of lesions",
            fontsize=10, fontweight="bold",
            color="#B22222" if label == "WORST" else "black")
        if column == 0:
            _legend(axes[column])

    _stamp(fig, "WEEK 3 — the best, the typical and the worst patient",
           "Averages hide failures, so here are the extremes. Green = expert, red = ours. "
           "Even the worst case finds the lesions; it disagrees about their edges.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.88))
    _save(fig, WEEK3 / "01-how-good-is-it" / "best-typical-and-worst-patient.png", commit, logger)


def figure_avd_failure(scores, commit, logger):
    """Explain the 102% volume error — a metric artefact, not a model failure."""
    key = "training_Utrecht_Utrecht_27"
    case = Case(key)
    row = scores[scores.subject_key == key].iloc[0]

    truth_voxels, pred_voxels = int(case.truth.sum()), int(case.pred.sum())
    false_positive = case.pred & ~case.truth
    distance = ndi.distance_transform_edt(~case.truth, sampling=case.spacing)
    near_fraction = float((distance[false_positive] <= 3).mean())

    coords = np.argwhere(case.truth[:, :, case.z])
    cy, cx = coords.mean(axis=0).astype(int)
    half = 55
    crop = ((max(0, cy - half), cy + half), (max(0, cx - half), cx + half))

    fig = plt.figure(figsize=(16, 5.6))
    grid = fig.add_gridspec(1, 4, width_ratios=[1, 1, 1, 1.25])

    axis = fig.add_subplot(grid[0, 0])
    case.panel(axis, show_pred=False, crop=crop)
    axis.set_title("TRUE lesions only\n(close-up)", fontsize=10,
                   color="#B22222", fontweight="bold")

    axis = fig.add_subplot(grid[0, 1])
    case.panel(axis, crop=crop)
    axis.set_title("ours on top\nedges slightly too generous", fontsize=10)
    _legend(axis)

    axis = fig.add_subplot(grid[0, 2])
    (x0, x1), (y0, y1) = crop
    # Explicit orange, not a colormap — "autumn" renders 1.0 as RED, which is
    # already the colour meaning "our prediction" in the panel to the left.
    from matplotlib.colors import ListedColormap
    overlay = np.where(false_positive[x0:x1, y0:y1, case.z], 1.0, np.nan)
    axis.imshow(case.norm[x0:x1, y0:y1, case.z].T[::-1], cmap="gray", vmin=0, vmax=2.0, alpha=0.55)
    axis.imshow(overlay.T[::-1], cmap=ListedColormap(["#FF8C00"]))
    axis.contour(case.truth[x0:x1, y0:y1, case.z].T[::-1], colors=TRUTH, linewidths=1.2)
    axis.set_title(f"only the EXTRA voxels (orange)\n{near_fraction:.0%} sit within 3 mm "
                   f"of a real lesion", fontsize=10)
    axis.axis("off")

    axis = fig.add_subplot(grid[0, 3])
    merged = scores.merge(_burden_table(), on="subject_key")
    axis.scatter(merged.lesion_ml, merged.avd_percent, s=26, color="#4C72B0", alpha=0.8)
    this = merged[merged.subject_key == key]
    axis.scatter(this.lesion_ml, this.avd_percent, s=120, color="#B22222",
                 zorder=5, label="this patient")
    axis.set_xscale("log")
    axis.set(xlabel="how much disease the patient has (mL, log scale)",
             ylabel="volume error (%)",
             title="why the score looks bad:\nsmall lesion load = huge % error")
    axis.legend(fontsize=8)
    axis.grid(alpha=0.3)

    _stamp(fig, "WEEK 3 — investigating the one patient with a 102% volume error",
           f"NOT a model failure. This patient has the 2nd-smallest lesion load of all 60 "
           f"({truth_voxels * case.voxel_volume / 1000:.2f} mL), so predicting "
           f"{(pred_voxels - truth_voxels) * case.voxel_volume / 1000:.2f} mL extra reads as "
           f"102% wrong. The network found 100% of the lesions.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.87))
    _save(fig, WEEK3 / "02-failure-cases" / "the-102-percent-volume-error-explained.png",
          commit, logger)


def _burden_table() -> pd.DataFrame:
    index = pd.read_csv(PROJECT_ROOT / "metadata" / "outputs" / "subject_index_week2.csv")
    index = index[index.week2_processed == True]  # noqa: E712
    return pd.DataFrame({"subject_key": index.subject_key,
                         "lesion_ml": index.lesion_volume_mm3 / 1000})


def figure_scores(scores, commit, logger):
    """Dice vs lesion F1 — the two disagree, and the reason matters."""
    fig, axes = plt.subplots(1, 3, figsize=(15.5, 4.8))
    colours = {"Amsterdam": "#4C72B0", "Singapore": "#DD8452", "Utrecht": "#55A868"}

    sites = list(colours)
    axes[0].bar([f"Method 1\n(cut-off)", "Method 2\n(network)"], [0.4291, 0.8056],
                color=["#999999", "#2E7D32"], width=0.55)
    for x, value in enumerate([0.4291, 0.8056]):
        axes[0].text(x, value + 0.02, f"{value:.3f}", ha="center", fontsize=12,
                     fontweight="bold")
    axes[0].set(ylim=(0, 1), ylabel="Dice (1.0 = perfect)",
                title="the headline improvement\n(patients never trained on)")
    axes[0].grid(axis="y", alpha=0.3)

    per_site = scores.groupby("site")[["dice", "lesion_f1"]].mean().reindex(sites)
    x = np.arange(len(sites))
    axes[1].bar(x - 0.2, per_site.dice, 0.4, label="Dice (how much volume we got right)",
                color="#2E7D32")
    axes[1].bar(x + 0.2, per_site.lesion_f1, 0.4,
                label="Lesion F1 (how many individual lesions)", color="#E8A33D")
    axes[1].set_xticks(x); axes[1].set_xticklabels(sites)
    axes[1].set(ylim=(0, 1), title="the same result, scored two ways")
    axes[1].legend(fontsize=8); axes[1].grid(axis="y", alpha=0.3)

    merged = scores.merge(_burden_table(), on="subject_key")
    for site, group in merged.groupby("site"):
        axes[2].scatter(group.lesion_ml, group.dice, s=26, label=site,
                        color=colours.get(site), alpha=0.85)
    axes[2].set_xscale("log")
    axes[2].set(xlabel="how much disease the patient has (mL, log scale)", ylabel="Dice",
                title="patients with little disease\nare harder to score well on")
    axes[2].legend(fontsize=8); axes[2].grid(alpha=0.3)

    _stamp(fig, "WEEK 3 — the numbers",
           "Middle panel is the important caveat: Dice counts VOLUME, lesion F1 counts "
           "INDIVIDUAL lesions. Singapore scores highest on volume but lowest on lesion "
           "count — it gets the big lesions right and misses small ones.", commit)
    fig.tight_layout(rect=(0, 0, 1, 0.87))
    _save(fig, WEEK3 / "01-how-good-is-it" / "the-numbers.png", commit, logger)


def main() -> None:
    logger = setup_logging(SCRIPT_NAME, OUTPUTS_DIR)
    commit = get_git_commit_hash()
    scores = pd.read_csv(OUTPUTS_DIR / "route_c_scores.csv")

    logger.info("writing Week 3 gallery to %s", WEEK3)
    figure_a_vs_c(scores, commit, logger)
    figure_best_and_worst(scores, commit, logger)
    figure_avd_failure(scores, commit, logger)
    figure_scores(scores, commit, logger)
    logger.info("done — %d figures", sum(1 for _ in WEEK3.rglob("*.png")))


if __name__ == "__main__":
    main()
